Demo_Login2/Demo_Login2/Models/Entities/KhoaDaoTao.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Demo_Login2.Models.Entities
{
    public class KhoaDaoTao
    {
        public int ID { get; set; }
        public string TenKhoaDaoTao { get; set; }
        public string NienKhoa { get; set; }
        public int? IDLoaiHinhDaoTao { get; set; }
        [ForeignKey("IDLoaiHinhDaoTao")]
        public LoaiHinhDaoTao LoaiHinhDaoTao { get; set; }
        public string GhiChu { get; set; }
        public ICollection<Account> Accounts_IDKhoaDaoTao { get; set; }
        public ICollection<LopHoc> LopHocs_IDKhoaDaoTao { get; set; }

    }
}

Demo_Login2/Demo_Login2/Areas/AdminPage/Controllers/KhoaDaoTaoController.cs
using Demo_Login2.Areas.AdminPage.Business;
using Demo_Login2.Models.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Demo_Login2.Areas.AdminPage.Controllers
{
    public class KhoaDaoTaoController : Controller
    {
        //LaydanhsachKhoaDaoTao
        public ActionResult Index()
        {
            var lstKhoa = this.LayDanhSachKhoaDaoTao();
            return View(lstKhoa);
        }
        public List<KhoaDaoTaoDTO> LayDanhSachKhoaDaoTao()
        {
            using(KhoaDaoTaoBusiness bs = new KhoaDaoTaoBusiness())
            {
                return bs.LayDanhSachKhoaDaoTao();
            }
        }
        //Get : TaoKhoaDaoTao
        public ActionResult Create()
        {
            ViewBag.loaihinhDT = new SelectList(LayDanhSachLoaiHinhDaoTao(), "ID", "TenLoaiHinh");
            return View();
        }
        //Post : TaoKhoaDaoTao
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(KhoaDaoTaoDTO khoadaotao)
        {
            var output = ThemKhoaDaoTao(khoadaotao);
            if (output)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View("Fail");
            }
        }

        public List<LoaiHinhDaoTaoDTO> LayDanhSachLoaiHinhDaoTao()
        {
            using(LoaiHinhDaoTaoBusiness bs = new LoaiHinhDaoTaoBusiness())
            {
                return bs.LayDanhSachLoaiHinhDaoTao();
            }
        }

        public bool ThemKhoaDaoTao(KhoaDaoTaoDTO khoadaotao)
        {
            using(KhoaDaoTaoBusiness bs = new KhoaDaoTaoBusiness())
            {
                return bs.ThemKhoaDaoTao(khoadaotao);
            }
        }
        
        //Get:SuaKhoaDaoTao
        public ActionResult Edit(int id)
        {
            ViewBag.loaihinhDT = new SelectList(LayDanhSachLoaiHinhDaoTao(), "ID", "TenLoaiHinh");
            KhoaDaoTaoDTO khoadaotao = LayKhoaDaoTao(id);
            return View(khoadaotao);
        }

        //Post:SuaKhoaDaoTao
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(KhoaDaoTaoDTO khoadaotao)
        {
            var output = SuaKhoaDaoTao(khoadaotao);
            if (output)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View("Fail");
            }
        }

        public KhoaDaoTaoDTO LayKhoaDaoTao(int id)
        {
            using(KhoaDaoTaoBusiness bs = new KhoaDaoTaoBusiness())
            {
                return bs.LayKhoaDaoTao(id);
            }
        }

        public bool SuaKhoaDaoTao(KhoaDaoTaoDTO khoadaotao)
        {
            using(KhoaDaoTaoBusiness bs = new KhoaDaoTaoBusiness())
            {
                return bs.SuaKhoaDaoTao(khoadaotao);
            }
        }

        //XoaKhoaDaoTao
        public async Task<ActionResult> Delete(int id)
        {
            var output = XoaKhoaDaoTao(id);
            if (output)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View("Fail");
            }
        }

        public bool XoaKhoaDaoTao(int id)
        {
            using (KhoaDaoTaoBusiness bs = new KhoaDaoTaoBusiness())
            {
                return bs.XoaKhoaDaoTao(id);
            }
        }

        //XemChiTietKhoaDaoTao
        public ActionResult Details(int id)
        {
            var khoa = LayKhoaDaoTao(id);
            ViewBag.loaihinhDT = new SelectList(LayDanhSachLoaiHinhDaoTao(), "ID", "TenLoaiHinh");
            return View(khoa);
        }
    }
}

Demo_Login2/Demo_Login2/Areas/AdminPage/Views/KhoaDaoTao/Create.cshtml
@model Demo_Login2.Models.DTO.KhoaDaoTaoDTO
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/AdminPage/Views/Shared/_AdminLayout.cshtml";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Khóa Đào Tạo</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "ThongKe")">Trang chủ</a></li>
                        <li class="breadcrumb-item active">Thêm Khóa Đào Tạo</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <section class="content">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.TenKhoaDaoTao, "Tên Khóa Đào Tạo", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TenKhoaDaoTao, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TenKhoaDaoTao, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.NienKhoa, "Niên Khóa", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.NienKhoa, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.NienKhoa, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.IDLoaiHinhDaoTao, "Loại Hình Đào Tạo", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.IDLoaiHinhDaoTao, @ViewBag.loaihinhDT as SelectList, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.IDLoaiHinhDaoTao, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.GhiChu, "Ghi chú", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Lưu" class="btn btn-default" />
                </div>
            </div>
        }
    </section>
    <div class="col-md-offset-2 col-md-3">
        <button class="btn btn-default" onclick="goBack()">Trở về</button>
    </div>
</div>

<script>
    function goBack() {
        window.history.back();
    }
</script>

Demo_Login2/Demo_Login2/Areas/AdminPage/Views/KhoaDaoTao/Details.cshtml
@model Demo_Login2.Models.DTO.KhoaDaoTaoDTO
@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/AdminPage/Views/Shared/_AdminLayout.cshtml";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Tài khoản</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "ThongKe")">Trang chủ</a></li>
                        <li class="breadcrumb-item active">Thêm tài khoản</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <section class="content">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.TenKhoaDaoTao, "Tên Khóa Đào Tạo", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DisplayFor(model => model.TenKhoaDaoTao, new { htmlAttributes = new { @class = "form-control" } })
                        
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.NienKhoa, "Niên Khóa", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DisplayFor(model => model.NienKhoa, new { htmlAttributes = new { @class = "form-control" } })
                        
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.IDLoaiHinhDaoTao, "Loại Hình Đào Tạo", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DisplayFor(model => model.IDLoaiHinhDaoTao, new { htmlAttributes = new { @class = "form-control" } })

                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.GhiChu, "Ghi chú", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DisplayFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control" } })
                        
                    </div>
                </div>
            </div>
        }
    </section>
    <div class="col-md-offset-2 col-md-3">
        <button class="btn btn-default" onclick="goBack()">Trở về</button>
    </div>
</div>

<script>
    function goBack() {
        window.history.back();
    }
</script>

Demo_Login2/Demo_Login2/Areas/AdminPage/Views/KhoaDaoTao/Edit.cshtml
@model Demo_Login2.Models.DTO.KhoaDaoTaoDTO
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/AdminPage/Views/Shared/_AdminLayout.cshtml";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Tài khoản</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "ThongKe")">Trang chủ</a></li>
                        <li class="breadcrumb-item active">Sửa khóa đào tạo</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <section class="content">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.TenKhoaDaoTao, "Tên Khóa Đào Tạo", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TenKhoaDaoTao, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TenKhoaDaoTao, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.NienKhoa, "Niên Khóa", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.NienKhoa, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.NienKhoa, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.IDLoaiHinhDaoTao, "Loại Hình Đào Tạo", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.IDLoaiHinhDaoTao, @ViewBag.loaihinhDT as SelectList, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.IDLoaiHinhDaoTao, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.GhiChu, "Ghi chú", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Lưu" class="btn btn-default" />
                </div>
            </div>
        }
    </section>
    <div class="col-md-offset-2 col-md-3">
        <button class="btn btn-default" onclick="goBack()">Trở về</button>
    </div>
</div>

<script>
    function goBack() {
        window.history.back();
    }
</script>

Demo_Login2/Demo_Login2/Areas/AdminPage/Views/KhoaDaoTao/Index.cshtml
@model List<Demo_Login2.Models.DTO.KhoaDaoTaoDTO>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/AdminPage/Views/Shared/_AdminLayout.cshtml";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Khóa Đào Tạo</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "ThongKe")">Trang chủ</a></li>
                        <li class="breadcrumb-item active">Khóa Đào Tạo</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <section class="content">
        <div class="card">
            <div class="card-header">
                <button class="btn btn-outline-primary" onclick="location.href='@Url.Action("Create","KhoaDaoTao")'">
                    <i class="fas fa-plus">
                        Thêm
                    </i>
                </button>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Tên Khóa Đào Tạo</th>
                            <th>Niên Khóa</th>
                            <th>Loại Hình Đào Tạo</th>
                            <th>Ghi Chú</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.TenKhoaDaoTao</td>
                                <td>@item.NienKhoa</td>
                                <td>@item.IDLoaiHinhDaoTao</td>
                                <td>@item.GhiChu</td>
                                <td>
                                    <button class="btn btn-outline-warning" onclick="location.href='@Url.Action("Edit","KhoaDaoTao",new {id = item.ID})'">
                                        <i class="fas fa-pen"></i>
                                        Sửa
                                    </button>
                                    <button class="btn btn-outline-danger btndeleteKhoaDaoTao" data-id="@item.ID">
                                        <i class="fas fa-trash"></i>
                                        Xóa
                                    </button>
                                    <button class="btn btn-outline-info" onclick="location.href='@Url.Action("Details","KhoaDaoTao",new {id = item.ID})'">
                                        <i class="fas fa-file-invoice"></i>
                                        Xem chi tiết
                                    </button>
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
        </div>
    </section>
</div>
<script src="~/Content/plugins/jquery/jquery.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#btnShowModal_Add").click(function () {
            $("#AddModal").modal('show');
        });

        $("#btnHideModal_Add").click(function () {
            $("#AddModal").modal('hide');
        });

        $(".btndeleteKhoaDaoTao").click(function () {
            var dataId = $(this).attr("data-id");
            swal({
                title: "Xác nhận?",
                text: "Bạn có chắc muốn xóa!!!",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
                .then((willDelete) => {
                    if (willDelete) {
                        window.location = "@Url.Action("Delete", "KhoaDaoTao")/" + dataId;

                        swal("Xóa thành công", {
                            icon: "success",
                        });
                    }
                });
        });
        
    });
</script>