Demo_Login2/Demo_Login2/Areas/AdminPage/Controllers/TaiKhoanController.cs
using Demo_Login2.Areas.AdminPage.Business;
using Demo_Login2.Models.DTO;
using Demo_Login2.Models.Entities;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Demo_Login2.Areas.AdminPage.Controllers
{
    public class TaiKhoanController : Controller
    {
        //LayDanhSachTaiKhoan
        public ActionResult Index()
        {
            var lstAccount = this.LayDanhSachTaiKhoan();
            return View(lstAccount);
        }

        public List<AccountDTO> LayDanhSachTaiKhoan()
        {
            using (TaiKhoanBusiness bs = new TaiKhoanBusiness())
            {
                return bs.LayDanhSachTaiKhoan();
            }
        }

        //Get: TaoTaiKhoan
        public ActionResult Create()
        {
            ViewBag.khoaDT = new SelectList(LayDanhSachKhoaDaoTao(), "ID", "TenKhoaDaoTao");
            return View();
        }
        //Post :TaoTaiKhoan
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(AccountDTO account)
        {
            var output = ThemTaiKhoan(account);
            if (output)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View("Fail");
            }
        }

        public List<KhoaDaoTaoDTO> LayDanhSachKhoaDaoTao()
        {
            using (KhoaDaoTaoBusiness bs = new KhoaDaoTaoBusiness())
            {
                return bs.LayDanhSachKhoaDaoTao();
            }
        }
        public bool ThemTaiKhoan(AccountDTO taikhoan)
        {
            using (TaiKhoanBusiness bs = new TaiKhoanBusiness())
            {
                return bs.ThemTaiKhoan(taikhoan);
            }
        }

        //Get: Suataikhoan
        public ActionResult Edit(int id)
        {
            ViewBag.khoaDT = new SelectList(LayDanhSachKhoaDaoTao(), "ID", "TenKhoaDaoTao");
            AccountDTO account = LayTaiKhoan(id);
            return View(account);
        }
        //Post : SuaTaiKhoan
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(AccountDTO account)
        {
            var output = SuaTaiKhoan(account);
            if (output)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View("fail");
            }
        }

        public AccountDTO LayTaiKhoan(int id)
        {
            using(TaiKhoanBusiness bs = new TaiKhoanBusiness())
            {
                return bs.LayTaiKhoan(id);
            }
        }
        public bool SuaTaiKhoan(AccountDTO taikhoan)
        {
            using (TaiKhoanBusiness bs = new TaiKhoanBusiness())
            {
                return bs.SuaTaiKhoan(taikhoan);
            }
        }

        //Xoataikhoan
        public async Task<ActionResult> Delete(int id)
        {
            var output = XoaTaiKhoan(id);
            if (output)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View("fail");
            }
        }

        public bool XoaTaiKhoan(int id)
        {
            using (TaiKhoanBusiness bs = new TaiKhoanBusiness())
            {
                return bs.XoaTaiKhoan(id);
            }
        }

        //Xemchitiet
        public ActionResult Details(int id)
        {
            var account = LayTaiKhoan(id);
            ViewBag.khoaDT = new SelectList(LayDanhSachKhoaDaoTao(), "ID", "TenKhoaDaoTao");
            return View(account);
        }


        //public ActionResult LayDanhSachTaiKhoan(dynamic dynamic)
        //{
        //    using (TaiKhoanBusiness bs = new TaiKhoanBusiness())
        //    {
        //        return View("Index", bs.LayDanhSachTaiKhoan());
        //    }

        //    using (KhoaDaoTaoBusiness bs = new KhoaDaoTaoBusiness())
        //    {
        //        return View("Index", bs.LayDanhSachKhoaDaoTao());
        //    }
        //}

        //public ActionResult LayTaiKhoan(int id)
        //{
        //    using (TaiKhoanBusiness bs = new TaiKhoanBusiness())
        //    {
        //        AccountDTO acc = bs.LayTaiKhoan(id);
        //        return View("Index",acc);
        //    }
        //}


        //public ActionResult ThemTaiKhoan(AccountDTO taikhoan)
        //{
        //    using (TaiKhoanBusiness bs = new TaiKhoanBusiness())
        //    {
        //        return View("Index",bs.ThemTaiKhoan(taikhoan));
        //    }
        //}

        //public ActionResult XoaTaiKhoan(int id)
        //{
        //    using (TaiKhoanBusiness bs = new TaiKhoanBusiness())
        //    {
        //        var result = bs.XoaTaiKhoan(id);
        //        if (result)
        //            return View("Successed");
        //        else
        //            return View("Failed");
        //    }
        //}

        //public ActionResult SuaTaiKhoan(AccountDTO taikhoan)
        //{
        //    using (TaiKhoanBusiness bs = new TaiKhoanBusiness())
        //    {
        //        return View("Index", bs.SuaTaiKhoan(taikhoan));
        //    }
        //}
    }
}

Demo_Login2/Demo_Login2/Areas/AdminPage/Views/TaiKhoan/Create.cshtml
@model Demo_Login2.Models.DTO.AccountDTO
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/AdminPage/Views/Shared/_AdminLayout.cshtml";
}

    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0">Tài khoản</h1>
                        <br />
                        <button class="btn btn-outline-warning" onclick="location.href='@Url.Action("Index", "TaiKhoan")'">
                            <i class="fas fa-arrow-left"></i>
                            back
                        </button>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="@Url.Action("Index", "ThongKe")">Trang chủ</a></li>
                            <li class="breadcrumb-item active">Thêm tài khoản</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <section class="content">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="form-horizontal">
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.Ma, "Mã", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Ma, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Ma, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.HoVaTen, "Họ và tên", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.HoVaTen, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.HoVaTen, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.MailVL, "Mail", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.MailVL, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.MailVL, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.IDKhoaDaoTao, "Khóa", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.IDKhoaDaoTao, @ViewBag.khoaDT as SelectList, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.IDKhoaDaoTao, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.PhanLoai, "Phân loại", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.PhanLoai, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.PhanLoai, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.DaXem, "Đã xem", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.DaXem, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DaXem, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.GhiChu, "Ghi chú", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        @*<input type="submit" value="Lưu" class="btn btn-default" />*@
                        <button class="btn btn-outline-success">
                            <i class="fas fa-check"></i>
                            Lưu
                        </button>
                    </div>
                </div>
            }
           
        </section>
        <div class="col-md-offset-2 col-md-3">
            
        </div>
    </div>

<script>
    function goBack() {
        window.history.back();
    }
</script>

Demo_Login2/Demo_Login2/Areas/AdminPage/Views/TaiKhoan/Details.cshtml
@model Demo_Login2.Models.DTO.AccountDTO
@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/AdminPage/Views/Shared/_AdminLayout.cshtml";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Tài khoản</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "ThongKe")">Trang chủ</a></li>
                        <li class="breadcrumb-item active">Chi tiết tài khoản</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <section class="content">
        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Ma, "Mã", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.Ma, new { htmlAttributes = new { @class = "form-control" } })

                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.HoVaTen, "Họ và tên", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.HoVaTen, new { htmlAttributes = new { @class = "form-control" } })

                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.MailVL, "Mail", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.MailVL, new { htmlAttributes = new { @class = "form-control" } })

                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.IDKhoaDaoTao, "Khóa", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.IDKhoaDaoTao, new { htmlAttributes = new { @class = "form-control" } })

                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.PhanLoai, "Phân loại", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.PhanLoai, new { htmlAttributes = new { @class = "form-control" } })

                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.DaXem, "Đã xem", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.DaXem, new { htmlAttributes = new { @class = "form-control" } })

                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.GhiChu, "Ghi chú", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control" } })

                </div>
            </div>
        </div>
    </section>
    <div class="col-md-offset-2 col-md-3">
        <button class="btn btn-default" onclick="goBack()">Trở về</button>
    </div>
</div>
<script>
    function goBack() {
        window.history.back();
    }
</script>

Demo_Login2/Demo_Login2/Areas/AdminPage/Views/TaiKhoan/Edit.cshtml
@model Demo_Login2.Models.DTO.AccountDTO
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/AdminPage/Views/Shared/_AdminLayout.cshtml";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Tài khoản</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "ThongKe")">Trang chủ</a></li>
                        <li class="breadcrumb-item active">Thêm tài khoản</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <section class="content">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Ma, "Mã", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Ma, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Ma, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.HoVaTen, "Họ và tên", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.HoVaTen, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.HoVaTen, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.MailVL, "Mail", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.MailVL, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MailVL, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.IDKhoaDaoTao, "Khóa", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.IDKhoaDaoTao, @ViewBag.khoaDT as SelectList, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.IDKhoaDaoTao, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.PhanLoai, "Phân loại", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.PhanLoai, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PhanLoai, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.DaXem, "Đã xem", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DaXem, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DaXem, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.GhiChu, "Ghi chú", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Lưu" class="btn btn-default" />
                </div>
            </div>
        }
    </section>
    <div class="col-md-offset-2 col-md-3">
        <button class="btn btn-default" onclick="goBack()">Trở về</button>
    </div>
</div>

<script>
    function goBack() {
        window.history.back();
    }
</script>