Demo_Login2/Demo_Login2/Models/Entities/LopHoc.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Demo_Login2.Models.Entities
{
    public class LopHoc
    {
        [Key]
        public int ID { get; set; }
        public int? IDKhoaDaoTao { get; set; }
        [ForeignKey("IDKhoaDaoTao")]
        public KhoaDaoTao KhoaDaoTao { get; set; }
        public string TenLop { get; set; }
        public string GhiChu { get; set; }
        public ICollection<AccountLopHoc> AccountLopHocs_IDLopHoc { get; set; }
    }
        
}

Demo_Login2/Demo_Login2/Areas/AdminPage/Controllers/LopHocController.cs
using Demo_Login2.Areas.AdminPage.Business;
using Demo_Login2.Models.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Demo_Login2.Areas.AdminPage.Controllers
{
    public class LopHocController : Controller
    {
        //LayDanhSachLopHoc
        public ActionResult Index()
        {
            var lstlophoc = this.LayDanhSachLopHoc();
            return View(lstlophoc);
        }

        public List<LopHocDTO> LayDanhSachLopHoc()
        {
            using (LopHocBusiness bs = new LopHocBusiness())
            {
                return bs.LayDanhSachLopHoc();
            }
        }

        //Get : TaoLopHoc
        public ActionResult Create()
        {
            ViewBag.khoaDT = new SelectList(LayDanhSachKhoaDaoTao(), "ID", "TenKhoaDaoTao");
            return View();
        }

        //Post : TaoLopHoc
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(LopHocDTO lophoc)
        {
            var output = ThemLopHoc(lophoc);
            if (output)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View("Fail");
            }
        }

        public List<KhoaDaoTaoDTO> LayDanhSachKhoaDaoTao()
        {
            using (KhoaDaoTaoBusiness bs = new KhoaDaoTaoBusiness())
            {
                return bs.LayDanhSachKhoaDaoTao();
            }
        }

        public bool ThemLopHoc(LopHocDTO lophoc)
        {
            using (LopHocBusiness bs = new LopHocBusiness())
            {
                return bs.ThemLopHoc(lophoc);
            }
        }

        //Get:SuaLopHoc
        public ActionResult Edit(int id)
        {
            ViewBag.khoaDT = new SelectList(LayDanhSachKhoaDaoTao(), "ID", "TenKhoaDaoTao");
            LopHocDTO lophoc = LayLopHoc(id);
            return View(lophoc);
        }

        //Post:SuaLopHoc
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(LopHocDTO lophoc)
        {
            var output = SuaLopHoc(lophoc);
            if (output)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View("Fail");
            }
        }

        public LopHocDTO LayLopHoc(int id)
        {
            using (LopHocBusiness bs = new LopHocBusiness())
            {
                return bs.LayLopHoc(id);
            }
        }

        public bool SuaLopHoc(LopHocDTO lophoc)
        {
            using (LopHocBusiness bs = new LopHocBusiness())
            {
                return bs.SuaLopHoc(lophoc);
            }
        }

        //XoaLopHoc
        public async Task<ActionResult> Delete(int id)
        {
            var output = XoaLopHoc(id);
            if (output)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View("Fail");
            }
        }

        public bool XoaLopHoc(int id)
        {
            using (LopHocBusiness bs = new LopHocBusiness())
            {
                return bs.XoaLopHoc(id);
            }
        }

        //XemChiTietLopHoc
        public ActionResult Details(int id)
        {
            var lophoc = LayLopHoc(id);
            ViewBag.khoaDT = new SelectList(LayDanhSachKhoaDaoTao(), "ID", "TenKhoaDaoTao");
            return View(lophoc);
        }
    }
}

Demo_Login2/Demo_Login2/Areas/AdminPage/Views/LopHoc/Create.cshtml
@model Demo_Login2.Models.DTO.LopHocDTO
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/AdminPage/Views/Shared/_AdminLayout.cshtml";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Lớp Học</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "ThongKe")">Trang chủ</a></li>
                        <li class="breadcrumb-item active">Thêm Lớp Học</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <section class="content">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.IDKhoaDaoTao, "Khóa Đào Tạo", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.IDKhoaDaoTao, @ViewBag.khoaDT as SelectList, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.IDKhoaDaoTao, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.TenLop, "Tên Lớp Học", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TenLop, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TenLop, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.GhiChu, "Ghi chú", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Lưu" class="btn btn-default" />
                </div>
            </div>
        }
    </section>
    <div class="col-md-offset-2 col-md-3">
        <button class="btn btn-default" onclick="goBack()">Trở về</button>
    </div>
</div>

<script>
    function goBack() {
        window.history.back();
    }
</script>

Demo_Login2/Demo_Login2/Areas/AdminPage/Views/LopHoc/Details.cshtml
@model Demo_Login2.Models.DTO.LopHocDTO
@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/AdminPage/Views/Shared/_AdminLayout.cshtml";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Lớp Học</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "ThongKe")">Trang chủ</a></li>
                        <li class="breadcrumb-item active">Chi tiết lớp học</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <section class="content">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.IDKhoaDaoTao, "Khóa Đào Tạo", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.IDKhoaDaoTao, new { htmlAttributes = new { @class = "form-control" } })

                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.TenLop, "Tên Lớp Học", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.TenLop, new { htmlAttributes = new { @class = "form-control" } })

                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.GhiChu, "Ghi chú", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control" } })

                </div>
            </div>
        </div>
        }
    </section>
    <div class="col-md-offset-2 col-md-3">
        <button class="btn btn-default" onclick="goBack()">Trở về</button>
    </div>
</div>

<script>
    function goBack() {
        window.history.back();
    }
</script>

Demo_Login2/Demo_Login2/Areas/AdminPage/Views/LopHoc/Edit.cshtml
@model Demo_Login2.Models.DTO.LopHocDTO
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/AdminPage/Views/Shared/_AdminLayout.cshtml";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Lớp Học</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "ThongKe")">Trang chủ</a></li>
                        <li class="breadcrumb-item active">Sửa Lớp Học</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <section class="content">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.IDKhoaDaoTao, "Khóa Đào Tạo", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.IDKhoaDaoTao, @ViewBag.khoaDT as SelectList, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.IDKhoaDaoTao, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.TenLop, "Tên Lớp Học", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TenLop, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TenLop, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.GhiChu, "Ghi chú", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Lưu" class="btn btn-default" />
                </div>
            </div>
        }
    </section>
    <div class="col-md-offset-2 col-md-3">
        <button class="btn btn-default" onclick="goBack()">Trở về</button>
    </div>
</div>

<script>
    function goBack() {
        window.history.back();
    }
</script>

Demo_Login2/Demo_Login2/Areas/AdminPage/Views/LopHoc/Index.cshtml
@model List<Demo_Login2.Models.DTO.LopHocDTO>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/AdminPage/Views/Shared/_AdminLayout.cshtml";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Lớp Học</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "ThongKe")">Trang chủ</a></li>
                        <li class="breadcrumb-item active">Lớp Học</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <section class="content">
        <div class="card">
            <div class="card-header">
                <button class="btn btn-outline-primary" onclick="location.href='@Url.Action("Create","LopHoc")'">
                    <i class="fas fa-plus">
                        Thêm
                    </i>
                </button>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Khóa Đào Tạo</th>
                            <th>Tên Lớp</th>
                            <th>Ghi Chú</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.IDKhoaDaoTao</td>
                                <td>@item.TenLop</td>
                                <td>@item.GhiChu</td>
                                <td>
                                    <button class="btn btn-outline-warning" onclick="location.href='@Url.Action("Edit","LopHoc",new {id = item.ID})'">
                                        <i class="fas fa-pen"></i>
                                        Sửa
                                    </button>
                                    <button class="btn btn-outline-danger btndeleteLopHoc" data-id="@item.ID">
                                        <i class="fas fa-trash"></i>
                                        Xóa
                                    </button>
                                    <button class="btn btn-outline-info" onclick="location.href='@Url.Action("Details","LopHoc",new {id = item.ID})'">
                                        <i class="fas fa-file-invoice"></i>
                                        Xem chi tiết
                                    </button>
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
        </div>
    </section>
</div>
<script src="~/Content/plugins/jquery/jquery.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#btnShowModal_Add").click(function () {
            $("#AddModal").modal('show');
        });

        $("#btnHideModal_Add").click(function () {
            $("#AddModal").modal('hide');
        });

        $(".btndeleteLopHoc").click(function () {
            var dataId = $(this).attr("data-id");
            swal({
                title: "Xác nhận?",
                text: "Bạn có chắc muốn xóa!!!",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
                .then((willDelete) => {
                    if (willDelete) {
                        window.location = "@Url.Action("Delete", "LopHoc")/" + dataId;

                        swal("Xóa thành công", {
                            icon: "success",
                        });
                    }
                });
        });

    });
</script>