Demo_Login2/Demo_Login2/Models/Entities/LoaiHinhDaoTao.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Demo_Login2.Models.Entities
{
    public class LoaiHinhDaoTao
    {
        [Key]
        public int ID { get; set; }
        public string TenLoaiHinh { get; set; }
        public string GhiChu { get; set; }
        public ICollection<KhoaDaoTao> KhoaDaoTaos_IDLoaiHinhDaoTao { get; set; }
    }
}

Demo_Login2/Demo_Login2/Areas/AdminPage/Controllers/LoaiHinhDaoTaoController.cs
using Demo_Login2.Areas.AdminPage.Business;
using Demo_Login2.Models.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Demo_Login2.Areas.AdminPage.Controllers
{
    public class LoaiHinhDaoTaoController : Controller
    {
        //LaydanhsachLoaiHinhDaoTao
        public ActionResult Index()
        {
            var lstloaihinhDT = this.LayDanhSachLoaiHinhDaoTao();
            return View(lstloaihinhDT);
        }
        public List<LoaiHinhDaoTaoDTO> LayDanhSachLoaiHinhDaoTao()
        {
            using(LoaiHinhDaoTaoBusiness bs = new LoaiHinhDaoTaoBusiness())
            {
                return bs.LayDanhSachLoaiHinhDaoTao();
            }
        }

        //Get : TaoLoaiHinhDaoTao
        public ActionResult Create()
        {
            return View();
        }
        //Post : TaoLoaiHinhDaoTao
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(LoaiHinhDaoTaoDTO loaihinhDT)
        {
            var output = ThemLoaiHinhDaoTao(loaihinhDT);
            if (output)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View("Fail");
            }
        }


        public bool ThemLoaiHinhDaoTao(LoaiHinhDaoTaoDTO loaihinhDT)
        {
            using(LoaiHinhDaoTaoBusiness bs = new LoaiHinhDaoTaoBusiness())
            {
                return bs.ThemLoaiHinhDaoTao(loaihinhDT);
            }
        }

        //Get : SuaLoaiHinhDaoTao
        public ActionResult Edit(int id)
        {
            LoaiHinhDaoTaoDTO loaihinhDT = LayLoaiHinhDaoTao(id);
            return View(loaihinhDT);
        }

        //Post : SuaLoaiHinhDaoTao
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(LoaiHinhDaoTaoDTO loaihinhDT)
        {
            var output = SuaLoaiHinhDaoTao(loaihinhDT);
            if (output)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View("Fail");
            }
        }

        public LoaiHinhDaoTaoDTO LayLoaiHinhDaoTao(int id)
        {
            using(LoaiHinhDaoTaoBusiness bs = new LoaiHinhDaoTaoBusiness())
            {
                return bs.LayLoaiHinhDaoTao(id);
            }
        }

        public bool SuaLoaiHinhDaoTao(LoaiHinhDaoTaoDTO loaihinhDT)
        {
            using(LoaiHinhDaoTaoBusiness bs = new LoaiHinhDaoTaoBusiness())
            {
                return bs.SuaLoaiHinhDaoTao(loaihinhDT);
            }
        }

        //XoaLoaiHinhDaoTao
        public async Task<ActionResult> Delete(int id)
        {
            var output = XoaLoaiHinhDaoTao(id);
            if (output)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View("Fail");
            }
        }

        public bool XoaLoaiHinhDaoTao(int id)
        {
            using (LoaiHinhDaoTaoBusiness bs = new LoaiHinhDaoTaoBusiness())
            {
                return bs.XoaLoaiHinhDaoTao(id);
            }
        }

        //XemChiTietLoaiHinhDaoTao
        public ActionResult Details(int id)
        {
            var loaihinhDT = LayLoaiHinhDaoTao(id);
            return View(loaihinhDT);
        }
    }
}

Demo_Login2/Demo_Login2/Areas/AdminPage/Views/LoaiHinhDaoTao/Create.cshtml
@model Demo_Login2.Models.DTO.LoaiHinhDaoTaoDTO
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/AdminPage/Views/Shared/_AdminLayout.cshtml";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Tạo Loại Hình Đào Tạo</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "ThongKe")">Trang chủ</a></li>
                        <li class="breadcrumb-item active">Tạo Loại Hình Đào Tạo</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <section class="content">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.TenLoaiHinh, "Tên Loại Hình Đào Tạo", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TenLoaiHinh, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TenLoaiHinh, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.GhiChu, "Ghi chú", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Lưu" class="btn btn-default" />
                </div>
            </div>
        }
    </section>
    <div class="col-md-offset-2 col-md-3">
        <button class="btn btn-default" onclick="goBack()">Trở về</button>
    </div>
</div>

<script>
    function goBack() {
        window.history.back();
    }
</script>

Demo_Login2/Demo_Login2/Areas/AdminPage/Views/LoaiHinhDaoTao/Details.cshtml
@model Demo_Login2.Models.DTO.LoaiHinhDaoTaoDTO
@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/AdminPage/Views/Shared/_AdminLayout.cshtml";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Chi Tiết Loại Hình Đào Tạo</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "ThongKe")">Trang chủ</a></li>
                        <li class="breadcrumb-item active">Chi Tiết Loại Hình Đào Tạo</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <section class="content">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.TenLoaiHinh, "Tên Loại Hình Đào Tạo", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DisplayFor(model => model.TenLoaiHinh, new { htmlAttributes = new { @class = "form-control" } })
                        
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.GhiChu, "Ghi chú", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DisplayFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control" } })
                        
                    </div>
                </div>
            </div>
           
        }
    </section>
    <div class="col-md-offset-2 col-md-3">
        <button class="btn btn-default" onclick="goBack()">Trở về</button>
    </div>
</div>

<script>
    function goBack() {
        window.history.back();
    }
</script>

Demo_Login2/Demo_Login2/Areas/AdminPage/Views/LoaiHinhDaoTao/Edit.cshtml
@model Demo_Login2.Models.DTO.LoaiHinhDaoTaoDTO
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/AdminPage/Views/Shared/_AdminLayout.cshtml";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Sửa Loại Hình Đào Tạo</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "ThongKe")">Trang chủ</a></li>
                        <li class="breadcrumb-item active">Sửa Loại Hình Đào Tạo</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <section class="content">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.TenLoaiHinh, "Tên Loại Hình Đào Tạo", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TenLoaiHinh, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TenLoaiHinh, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.GhiChu, "Ghi chú", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Lưu" class="btn btn-default" />
                </div>
            </div>
        }
    </section>
    <div class="col-md-offset-2 col-md-3">
        <button class="btn btn-default" onclick="goBack()">Trở về</button>
    </div>
</div>

<script>
    function goBack() {
        window.history.back();
    }
</script>

Demo_Login2/Demo_Login2/Areas/AdminPage/Views/LoaiHinhDaoTao/Index.cshtml
@model List<Demo_Login2.Models.DTO.LoaiHinhDaoTaoDTO>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/AdminPage/Views/Shared/_AdminLayout.cshtml";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Loại Hình Đào Tạo</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "ThongKe")">Trang chủ</a></li>
                        <li class="breadcrumb-item active">Loại Hình Đào Tạo</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <section class="content">
        <div class="card">
            <div class="card-header">
                <button class="btn btn-outline-primary" onclick="location.href='@Url.Action("Create","LoaiHinhDaoTao")'">
                    <i class="fas fa-plus">
                        Thêm
                    </i>
                </button>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Tên Loại Hình Đào Tạo</th>
                            <th>Ghi Chú</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.TenLoaiHinh</td>
                                <td>@item.GhiChu</td>
                                <td>
                                    <button class="btn btn-outline-warning" onclick="location.href='@Url.Action("Edit","LoaiHinhDaoTao",new {id = item.ID})'">
                                        <i class="fas fa-pen"></i>
                                        Sửa
                                    </button>
                                    <button class="btn btn-outline-danger btndeleteLoaiHinhDaoTao" data-id="@item.ID">
                                        <i class="fas fa-trash"></i>
                                        Xóa
                                    </button>
                                    <button class="btn btn-outline-info" onclick="location.href='@Url.Action("Details","LoaiHinhDaoTao",new {id = item.ID})'">
                                        <i class="fas fa-file-invoice"></i>
                                        Xem chi tiết
                                    </button>
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
        </div>
    </section>
</div>
<script src="~/Content/plugins/jquery/jquery.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#btnShowModal_Add").click(function () {
            $("#AddModal").modal('show');
        });

        $("#btnHideModal_Add").click(function () {
            $("#AddModal").modal('hide');
        });

        $(".btndeleteLoaiHinhDaoTao").click(function () {
            var dataId = $(this).attr("data-id");
            swal({
                title: "Xác nhận?",
                text: "Bạn có chắc muốn xóa!!!",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
                .then((willDelete) => {
                    if (willDelete) {
                        window.location = "@Url.Action("Delete", "LoaiHinhDaoTao")/" + dataId;

                        swal("Xóa thành công", {
                            icon: "success",
                        });
                    }
                });
        });

    });
</script>